services:
  db:
    image: postgres:16-alpine
    container_name: pos_db_local
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: pos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: pos_backend_local
    restart: always
    environment:
      - DATABASE_URL=postgresql://admin:password123@db:5432/pos_db
      - DEPLOYMENT_MODE=SERVER
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    build:
      context: ./front
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000/api/v1
    container_name: pos_front_local
    restart: always
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: