"""Add session payments and refund support

Revision ID: 5169a39e7093
Revises: 0e042d04991d
Create Date: 2026-02-07 17:41:46.723795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5169a39e7093'
down_revision: Union[str, Sequence[str], None] = '0e042d04991d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'TRANSFER', 'MIXED', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)

    op.drop_table('_alembic_tmp_inventory_movements')
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('expected_cash', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_sales_transfer', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('difference', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('initial_cash',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('is_open',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('inventory_movement_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_before', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('stock_after', sa.Float(), nullable=False))
        batch_op.alter_column('movement_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('purchase_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('IN_PURCHASE', 'IN_RETURN', 'IN_ADJUSTMENT', 'OUT_SALE', 'OUT_WASTE', 'OUT_ADJUSTMENT', 'INTERNAL_TRANSFER', name='movementtype'),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'purchases', ['purchase_id'], ['id'])
        batch_op.create_foreign_key(None, 'tickets', ['ticket_id'], ['id'])

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_product_categories_id'), ['id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('internal_reference',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('uom',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'unidades'"))
        batch_op.alter_column('stock_quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('min_stock',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'product_categories', ['category_id'], ['id'])

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percent', sa.Float(), nullable=True))
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_number', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('date_validated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.Enum('DRAFT', 'VALIDATED', 'PAID', 'REFUNDED', 'CANCELLED', name='salestate'), nullable=False))
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('refund_ticket_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('original_ticket_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refund_reason', sa.Enum('RETURN_TO_STOCK', 'DAMAGED', 'CUSTOMER_ERROR', 'SYSTEM_ERROR', name='refundreason'), nullable=True))
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_tickets_ticket_number'), ['ticket_number'], unique=True)
        batch_op.create_foreign_key(None, 'tickets', ['original_ticket_id'], ['id'])
        batch_op.create_foreign_key(None, 'tickets', ['refund_ticket_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tickets_ticket_number'))
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('refund_reason')
        batch_op.drop_column('original_ticket_id')
        batch_op.drop_column('refund_ticket_id')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('state')
        batch_op.drop_column('date_validated')
        batch_op.drop_column('ticket_number')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('discount_percent')

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('min_stock',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('stock_quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('uom',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'unidades'"))
        batch_op.alter_column('internal_reference',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_categories_id'))
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('type',
               existing_type=sa.Enum('IN_PURCHASE', 'IN_RETURN', 'IN_ADJUSTMENT', 'OUT_SALE', 'OUT_WASTE', 'OUT_ADJUSTMENT', 'INTERNAL_TRANSFER', name='movementtype'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('purchase_id')
        batch_op.drop_column('ticket_id')

    with op.batch_alter_table('inventory_movement_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('movement_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('stock_after')
        batch_op.drop_column('stock_before')

    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.alter_column('is_open',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('initial_cash',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('difference')
        batch_op.drop_column('total_sales_transfer')
        batch_op.drop_column('expected_cash')
        batch_op.drop_column('name')

    op.create_table('_alembic_tmp_inventory_movements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=17), nullable=False),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    # ### end Alembic commands ###
