"""add_matrix_locations_and_category_color

Revision ID: a0a3ffde7d8d
Revises: 5169a39e7093
Create Date: 2026-02-10 21:12:29.583693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a3ffde7d8d'
down_revision: Union[str, Sequence[str], None] = '5169a39e7093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('side', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('column', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_locations', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('column')
        batch_op.drop_column('side')
        batch_op.drop_column('zone')

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
