"""Add work order and tickets relation

Revision ID: b6141b3e5b45
Revises: b6268bd94a88
Create Date: 2026-03-01 16:18:43.868448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6141b3e5b45'
down_revision: Union[str, Sequence[str], None] = 'b6268bd94a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('work_order_id', sa.UUID(), nullable=True))
    op.add_column('tickets', sa.Column('ticket_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_tickets_work_order_id'), 'tickets', ['work_order_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'work_orders', ['work_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_work_order_id'), table_name='tickets')
    op.drop_column('tickets', 'ticket_type')
    op.drop_column('tickets', 'work_order_id')
    # ### end Alembic commands ###
